title: DSC Sharda University
theme: minima
author: DSC Sharda University
email: singh08prashant@gmail.com
description: Developer Student Clubs (DSC) are community groups for students from any academic background in their undergraduate or graduate term. 
By joining a DSC, students build their professional and personal network, get access to Google developer resources,
and work together to build solutions for local problems in a peer-to-peer learning environment.

# social links
twitter_username: @s08prashant
github_username:  singh-08-prashant

show_excerpts: true # set to false to remove excerpts on the homepage
